import { DealItem, MenuItem, PropertyInfo, StaffTicket, UserProfile } from "@shared/airpal-data";

/**
 * PURE DEMO DATASET
 * Completely isolated from real production databases, real user accounts, and real hotels.
 */

export const DEMO_PROPERTIES: PropertyInfo[] = [
  {
    id: "demo-grand-harbour",
    name: "Grand Harbour Hotel & Suites",
    kind: "hotel",
    tagline: "5-Star Waterfront Luxury on Sydney Harbour",
    destination: "Sydney Harbour Front",
    city: "Sydney",
    country: "Australia",
    address: "88 George St, The Rocks, Sydney NSW 2000",
    phone: "+61 2 9250 6000",
    whatsapp: "+61 400 123 456",
    roomsCount: 140,
    status: "active",
    ownerEmail: "demo.host@harbourgrand.com",
    monthlyRevenue: 54800,
    plan: "Enterprise",
    wifi: {
      network: "GrandHarbour_Guest_HighSpeed",
      password: "HarbourLuxury2026",
      speed: "1 Gbps Fiber",
    },
    checkIn: "2:00 PM",
    checkOut: "11:00 AM",
    breakfast: {
      hours: "6:30 AM – 10:30 AM",
      location: "Level 2 Waterside Atrium",
      type: "Full Continental & Artisan Buffet",
      price: "Complimentary for Club Rooms",
    },
    facilities: [
      { name: "Infinity Pool & Cabanas", hours: "6:00 AM – 10:00 PM", floor: "Rooftop (Level 28)", details: "Heated harbour views", icon: "Waves" },
      { name: "Harbour Spa & Wellness", hours: "8:00 AM – 8:00 PM", floor: "Level 4", details: "Remedial massage & sauna", icon: "Sparkles" },
      { name: "24/7 Technogym Center", hours: "24 Hours", floor: "Level 4", details: "Keycard access", icon: "Dumbbell" },
      { name: "Concierge & Valet", hours: "24 Hours", floor: "Ground Lobby", details: "Instant car retrieval", icon: "BellRing" },
    ],
  },
  {
    id: "demo-heritage-rocks",
    name: "The Heritage Boutique Sydney",
    kind: "hotel",
    tagline: "Historic Sandstone Elegance in The Rocks",
    destination: "The Rocks Precinct",
    city: "Sydney",
    country: "Australia",
    address: "14 Argyle Place, Millers Point NSW 2000",
    phone: "+61 2 9247 1100",
    whatsapp: "+61 400 987 654",
    roomsCount: 48,
    status: "active",
    ownerEmail: "gm@heritageboutique.com",
    monthlyRevenue: 28400,
    plan: "Professional",
    wifi: {
      network: "Heritage_Rocks_Guest",
      password: "Sandstone1840",
      speed: "500 Mbps",
    },
    checkIn: "3:00 PM",
    checkOut: "10:00 AM",
    breakfast: {
      hours: "7:00 AM – 11:00 AM",
      location: "Courtyard Garden Cafe",
      type: "Farm-to-Table A La Carte",
      price: "$28 AUD",
    },
    facilities: [
      { name: "Sandstone Wine Cellar", hours: "4:00 PM – 11:00 PM", floor: "Basement Vault", details: "Curated Australian vintages", icon: "Wine" },
      { name: "Quiet Library Lounge", hours: "24 Hours", floor: "Level 1", details: "Complimentary tea & coffee", icon: "BookOpen" },
    ],
  },
  {
    id: "demo-snowy-peak",
    name: "Snowy Peak Alpine Resort",
    kind: "hotel",
    tagline: "Ski-in Ski-out Alpine Chalets & Heated Pools",
    destination: "Perisher Valley",
    city: "Snowy Mountains",
    country: "Australia",
    address: "12 Alpine Way, Perisher NSW 2624",
    phone: "+61 2 6457 2000",
    whatsapp: "+61 400 555 777",
    roomsCount: 64,
    status: "trial",
    ownerEmail: "alpine@snowypeak.com",
    monthlyRevenue: 36200,
    plan: "Starter",
    wifi: {
      network: "SnowyPeak_Chalet_Guest",
      password: "PowderDay2026",
      speed: "250 Mbps",
    },
    checkIn: "2:00 PM",
    checkOut: "10:00 AM",
    breakfast: {
      hours: "6:00 AM – 9:30 AM",
      location: "Fireside Lodge",
      type: "Hot Alpine Buffet",
      price: "Included",
    },
    facilities: [
      { name: "Ski Valet & Dry Room", hours: "7:00 AM – 8:00 PM", floor: "Ground Floor", details: "Heated boot racks", icon: "Snowflake" },
      { name: "Outdoor Heated Jacuzzis", hours: "8:00 AM – 10:00 PM", floor: "Alpine Deck", details: "Mountain slope views", icon: "Thermometer" },
    ],
  },
];

export const DEMO_DEALS: DealItem[] = [
  {
    id: "deal-rooftop-champagne",
    propertyId: "demo-grand-harbour",
    title: "Sunset Rooftop Champagne Experience",
    subtitle: "Chilled Veuve Clicquot and fresh Sydney rock oysters at twilight.",
    badge: "Save 30%",
    discountBadge: "Save 30%",
    price: 65,
    originalPrice: 95,
    iconName: "Wine",
    category: "dining",
    active: true,
    expiresAt: "Tonight 7:30 PM",
  },
  {
    id: "deal-harbour-catamaran",
    propertyId: "demo-grand-harbour",
    title: "Private Sunset Sailing Catamaran",
    subtitle: "2-hour private yacht cruise under the Sydney Harbour Bridge.",
    badge: "Save $150",
    discountBadge: "Save $150",
    price: 450,
    originalPrice: 600,
    iconName: "Ship",
    category: "transport",
    active: true,
    expiresAt: "Tomorrow 5:00 PM",
  },
  {
    id: "deal-spa-hydrotherapy",
    propertyId: "demo-grand-harbour",
    title: "Signature Spa & Hydrotherapy Pass",
    subtitle: "60-minute hot stone massage with private sauna access.",
    badge: "Save 25%",
    discountBadge: "Save 25%",
    price: 120,
    originalPrice: 160,
    iconName: "Sparkles",
    category: "wellness",
    active: true,
    expiresAt: "Limited daily passes",
  },
  {
    id: "deal-late-checkout",
    propertyId: "demo-grand-harbour",
    title: "Late 2:00 PM Checkout Pass",
    subtitle: "Sleep in comfortably and enjoy an unhurried morning departure.",
    badge: "Popular",
    discountBadge: "Popular",
    price: 40,
    originalPrice: 60,
    iconName: "Clock",
    category: "stay",
    active: true,
  },
];

export const DEMO_MENU: MenuItem[] = [
  {
    id: "menu-wagyu-burger",
    propertyId: "demo-grand-harbour",
    name: "Truffle Wagyu Beef Burger",
    description: "200g grain-fed MS6+ Wagyu beef patty, double Gruyère, black truffle aioli, brioche bun, rosemary fries.",
    price: 28,
    category: "Mains",
    dietary: ["Chef Pick"],
    available: true,
  },
  {
    id: "menu-bondi-bowl",
    propertyId: "demo-grand-harbour",
    name: "Bondi Superfood Harvest Bowl",
    description: "Avocado, roasted turmeric cauliflower, edamame, organic quinoa, wild rocket, tahini lemon dressing.",
    price: 22,
    category: "Mains",
    dietary: ["Vegan", "Gluten Free"],
    available: true,
  },
  {
    id: "menu-tasmanian-salmon",
    propertyId: "demo-grand-harbour",
    name: "Crispy Skin Tasmanian Salmon",
    description: "Pan-seared Atlantic salmon, asparagus spears, celeriac silk puree, dill beurre blanc.",
    price: 36,
    category: "Mains",
    dietary: ["Gluten Free"],
    available: true,
  },
  {
    id: "menu-artisan-pizza",
    propertyId: "demo-grand-harbour",
    name: "Bufala Margherita Woodfired Pizza",
    description: "San Marzano D.O.P. tomato base, fresh buffalo mozzarella, fragrant basil leaves, cold-pressed olive oil.",
    price: 24,
    category: "Mains",
    dietary: ["Vegetarian"],
    available: true,
  },
  {
    id: "menu-barossa-shiraz",
    propertyId: "demo-grand-harbour",
    name: "Barossa Valley Old Vine Shiraz 2021",
    description: "Rich dark berry notes, hint of French oak, velvety tannins. Bottle (750ml).",
    price: 68,
    category: "Drinks",
    dietary: [],
    available: true,
  },
  {
    id: "menu-chocolate-cake",
    propertyId: "demo-grand-harbour",
    name: "Warm Valrhona Molten Fondant",
    description: "Dark Belgian chocolate lava center, Madagascar vanilla bean gelato, candied hazelnut praline.",
    price: 16,
    category: "Desserts",
    dietary: ["Vegetarian"],
    available: true,
  },
];

export const DEMO_TICKETS: StaffTicket[] = [
  {
    id: "t-demo-101",
    propertyId: "demo-grand-harbour",
    roomNumber: "508",
    guestName: "Emma Watson",
    category: "housekeeping",
    details: "Extra goose down pillows and plush bath sheets requested before 6:00 PM.",
    status: "resolved",
    createdAt: "2026-09-06T09:15:00Z",
    urgency: "normal",
  },
  {
    id: "t-demo-102",
    propertyId: "demo-grand-harbour",
    roomNumber: "312",
    guestName: "David Miller",
    category: "reception",
    details: "Airport VIP limousine transfer departing lobby at 6:45 AM tomorrow morning.",
    status: "in_progress",
    createdAt: "2026-09-06T11:30:00Z",
    urgency: "urgent",
  },
  {
    id: "t-demo-103",
    propertyId: "demo-grand-harbour",
    roomNumber: "204",
    guestName: "Sophia Rossi",
    category: "dining",
    details: "Champagne bucket & crystal flutes delivery to celebrate wedding anniversary.",
    status: "pending",
    createdAt: "2026-09-06T15:20:00Z",
    urgency: "urgent",
  },
  {
    id: "t-demo-104",
    propertyId: "demo-grand-harbour",
    roomNumber: "418",
    guestName: "Liam Zhang",
    category: "maintenance",
    details: "Thermostat calibrated to 21°C upon guest request.",
    status: "resolved",
    createdAt: "2026-09-06T08:00:00Z",
    urgency: "normal",
  },
];

export const DEMO_PERSONAS = [
  {
    role: "super_admin" as const,
    title: "Platform Super Admin",
    email: "demo.admin@airpal.me",
    displayName: "Alexander Thorne (Platform Owner)",
    description: "Oversee all registered hotels, platform commission, cross-property analytics, and onboarding.",
    defaultRoute: "/demo/admin",
    badgeColor: "bg-purple-100 text-purple-800 border-purple-200",
  },
  {
    role: "host_admin" as const,
    title: "Hotel General Manager",
    email: "demo.host@harbourgrand.com",
    displayName: "Eleanor Vance (GM Grand Harbour)",
    description: "Manage deals & offers studio, dining menus, Wi-Fi compendium, ticket queues, and revenue.",
    defaultRoute: "/demo/host",
    badgeColor: "bg-amber-100 text-amber-800 border-amber-200",
  },
  {
    role: "staff" as const,
    title: "Front Desk & Concierge",
    email: "demo.staff@harbourgrand.com",
    displayName: "Liam Chen (Chief Concierge)",
    description: "Resolve incoming guest requests in real time, view ticket queues, and manage room services.",
    defaultRoute: "/demo/host",
    badgeColor: "bg-blue-100 text-blue-800 border-blue-200",
  },
  {
    role: "guest" as const,
    title: "In-House Guest (Room 508)",
    email: "demo.guest@harbourgrand.com",
    displayName: "Sophia Rossi (Guest Room 508)",
    description: "Experience the guest room mobile companion: 1-tap Wi-Fi, dining ordering, deals, and local picks.",
    defaultRoute: "/demo/stay",
    badgeColor: "bg-emerald-100 text-emerald-800 border-emerald-200",
  },
];
